version: 2.1

orbs:
  stack-build: pbrisbin/stack-build@3.0.0
  docker-build-cached: pbrisbin/docker-build-cached@1.0.0
  aws-cli: circleci/aws-cli@1.2.1
  heroku-container: pbrisbin/heroku-container@1.0.0
  pushover: pbrisbin/pushover@1.0.0

executors:
  default:
    docker:
      - image: fpco/stack-build:lts-14.6
      - image: circleci/postgres:9.6.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: restyled_test
      - image: redis:4.0.2-alpine

jobs:
  update-stack-image:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Update CloudFormation Stack
          command: |
            image=restyled/restyled.io:${CIRCLE_SHA1:0:10}
            aws cloudformation update-stack \
              --stack-name prod-services \
              --use-previous-template \
              --parameters \
                "ParameterKey=Environment,UsePreviousValue=true" \
                "ParameterKey=RestylerImage,UsePreviousValue=true" \
                "ParameterKey=AppsWebhooksDesiredCount,UsePreviousValue=true" \
                "ParameterKey=RestyledImage,ParameterValue=$image" \
              --capabilities CAPABILITY_NAMED_IAM
            aws cloudformation wait stack-update-complete \
              --stack-name prod-services

references:
  master_only: &master_only
    filters:
      branches:
        only:
          - master

workflows:
  build_and_release:
    jobs:
      - stack-build/build-test-lint:
          name: build
          install-stack: false
          upgrade-stack: true
          before-dependencies:
            - run: stack build --no-terminal -j 1 Cabal aeson haskell-src-exts
          after-dependencies:
            - run: stack install --no-terminal --copy-compiler-tool dbmigrations-postgresql
          before-test:
            - run: db/migrate test upgrade
          hlint-yaml-url:
            https://raw.githubusercontent.com/pbrisbin/dotfiles/master/hlint.yaml
          executor: default

      - docker-build-cached/build-and-release:
          name: image
          registry-username: DOCKERHUB_USERNAME
          registry-password: DOCKERHUB_PASSWORD
          image: restyled/restyled.io
          build-stages: builder
          extra-build-arguments: '--build-arg "REVISION=$CIRCLE_SHA1"'

      - heroku-container/push-and-release:
          <<: *master_only
          name: release-frontend
          requires: [build, image]
          app-name: restyled-io
          recursive: true
          before-build:
            - run: |
                cat >Dockerfile.web \<<EOM
                FROM restyled/restyled.io:${CIRCLE_SHA1:0:10}
                CMD ["/app/restyled.io", "web"]
                EOM
          context: deploy-heroku

      - update-stack-image:
          <<: *master_only
          name: release-backend
          requires: [build, image]
          context: deploy-aws

      - pushover/notify:
          <<: *master_only
          name: notify
          requires: [release-frontend, release-backend]
          title: 'Restyled deployments'
          message: 'restyled.io deployed at ${CIRCLE_SHA1:0:10}'
