---
version: 2.0

jobs:
  tests:
    docker:
      - image: fpco/stack-build:lts
      - image: circleci/postgres:9.6.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: restyled_test
      - image: redis:4.0.2-alpine
    steps:
      - checkout
      - run:
          name: Digest
          command: git ls-files | xargs md5sum > digest
      - restore_cache:
          keys:
            - v1-{{ .Branch }}-{{ checksum "digest" }}
            - v1-{{ .Branch }}
            - v1-
      - run:
          name: Dependencies
          command: make setup
      - run:
          name: Build
          command: make build
      - run:
          name: Lint
          command: |
            curl -o .hlint.yaml \
              https://raw.githubusercontent.com/pbrisbin/dotfiles/master/hlint.yaml
            make lint
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "digest" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Test
          command: make test

  image:
    docker:
      - image: docker:17.07.0-ce
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          version: 17.07.0-ce
      - run:
          name: Dependencies
          command: apk add --update git make
      - run:
          name: Build image
          command: |
            make image.build
      - run:
          name: Push image
          command: |
            make image.release \
              DOCKER_USERNAME=$DOCKERHUB_USERNAME \
              DOCKER_PASSWORD=$DOCKERHUB_PASSWORD \
              RELEASE_IMAGE=restyled/restyled.io:b$CIRCLE_BUILD_NUM

      - run:
          name: Record image tag
          command: |
            mkdir -p /tmp/workspace
            echo "b$CIRCLE_BUILD_NUM" > /tmp/workspace/image-tag

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - image-tag

  deploy:
    docker:
      - image: restyled/ops
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          reusable: true
          version: 17.07.0-ce
      - deploy:
          name: Deploy
          command: |
            read -r image_tag < /tmp/workspace/image-tag
            release-restyled "$image_tag"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - tests
      - image:
          context: org-global
      - deploy:
          context: org-global
          filters:
            branches:
              only: master
          requires:
            - tests
            - image
