# yamllint disable rule:line-length
version: 2.0

jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-13.3
        environment:
          STACK_ARGUMENTS: --no-terminal
      - image: circleci/postgres:9.6.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: restyled_test
      - image: redis:4.0.2-alpine
    steps:
      - checkout
      - run:
          name: Digest
          command: git ls-files | xargs md5sum > digest
      - restore_cache:
          keys:
            - v5-{{ .Branch }}-{{ checksum "stack.yaml" }}-{{ checksum "digest" }}
            - v5-{{ .Branch }}-{{ checksum "stack.yaml" }}-
            - v5-{{ .Branch }}
            - v5-
      - run:
          name: Dependencies
          command: make setup setup.lint
      - run:
          name: Build
          command: make build
      - save_cache:
          key: v5-{{ .Branch }}-{{ checksum "stack.yaml" }}-{{ checksum "digest" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Migrate
          command: db/migrate test upgrade
      - run:
          name: Test
          command: make test
      - run:
          name: Lint
          command: make lint

  image:
    docker:
      - image: quay.io/restyled-io/ops
    steps:
      - checkout
      - setup_remote_docker:
         docker_layer_caching: true
      - run:
          name: Build
          command: |
            sha=${CIRCLE_SHA1:0:10}
            release_image=quay.io/restyled-io/restyled.io:$sha
            docker build --tag "$release_image" .
            docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io
            docker push "$release_image"

  release:
    docker:
      - image: quay.io/restyled-io/ops
    steps:
      - setup_remote_docker:
         docker_layer_caching: true
      - run:
          name: Release
          command: |
            sha=${CIRCLE_SHA1:0:10}
            release_image=quay.io/restyled-io/restyled.io:$sha
            services=(web webhooks retries)

            for service in "${services[@]}"; do
              cat >"Dockerfile.$service" <<EOM
            FROM $release_image
            CMD ["/app/restyled.io", "$service"]
            EOM
            done

            heroku container:login
            heroku container:push --recursive --app restyled-io
            heroku container:release "${services[@]}" --app restyled-io
            notify "restyled-io" "Deployed at $sha"

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - image
      - release:
          requires:
            - build
            - image
          filters:
            branches:
              only:
                - master
