version: 2.0

jobs:
  build_and_test:
    docker:
      - image: fpco/stack-build:lts
        environment:
          GIT_AUTHOR_EMAIL: ci@restyled.io
          GIT_AUTHOR_NAME: Restyled.io CI
          GIT_COMMITTER_EMAIL: ci@restyled.io
      - image: circleci/postgres:9.6.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: restyled_test
      - image: redis:4.0.2-alpine
    steps:
      - checkout
      - restore_cache:
          keys: stack
            - stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
            - stack-{{ .Branch }}
            - stack
      - run:
          name: Dependencies
          command: make setup
      - run:
          name: Build
          command: make build
      - run:
          name: Lint
          command: make lint
      - save_cache:
          key: stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Test
          command: make test.ci

  deploy:
    docker:
      - image: docker:17.07.0-ce
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          version: 17.07.0-ce
      - run:
          name: Dependencies
          command: apk add --update git make
      - run:
          name: Build image
          command: make image.build
      - deploy:
          name: Docker Hub
          command: |
              make image.release \
                DOCKER_USERNAME=$DOCKERHUB_USERNAME \
                DOCKER_PASSWORD=$DOCKERHUB_PASSWORD \
                RELEASE_IMAGE=restyled/restyled:b$CIRCLE_BUILD_NUM

              if [[ "$CIRCLE_BRANCH" == master ]]; then
                docker run \
                  --env AWS_ACCESS_KEY_ID \
                  --env AWS_SECRET_ACCESS_KEY \
                  "restyled/restyled:b$CIRCLE_BUILD_NUM" \
                  /app/ops deploy \
                  --stack-name RestyledProd \
                  --image-tag "b$CIRCLE_BUILD_NUM"
              fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
