version: 2.0

jobs:
  build_and_test:
    docker:
      - image: fpco/stack-build:lts
      - image: circleci/postgres:9.4.12-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: restyled_test
    steps:
      - checkout
      - restore_cache:
          keys: stack
            - stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
            - stack-{{ .Branch }}
            - stack
      - run:
          name: Dependencies
          command: make setup
      - run:
          name: Build
          command: make build
      - run:
          name: Lint
          command: make lint
      - save_cache:
          key: stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Test
          command: make test

  deploy:
    docker:
      - image: docker:17.07.0-ce
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.07.0-ce
      - run:
          name: Dependencies
          command: apk add --update make
      # N.B. no caching because it's too large. we just have to wait.
      - run:
          name: Build image
          command: make image.build
      - deploy:
          name: Staging
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              make image.release \
                DOCKER_USERNAME=$HEROKU_EMAIL \
                DOCKER_PASSWORD=$HEROKU_API_KEY
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
